a = ["zack", "mary", "tom", "json", "Burke", ["Berg", "Benton"]]
b = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(a)
a.insert(1, "apple")
print(a)
a.append("li",)
print(a)
a.remove("li")
print(a)
a.remove(a[2])
print(a)
c = a.pop(1)
print("pop", a)
print("c=", c)
a.remove(["Berg", "Benton"])
print(a)
print(a.index("tom"))
a.sort()
print(a)
print(b)
b.sort()
print(b)
b.reverse()
print(b)

# print(a[1])
# print(a[0:2])
# print(a[0::3])
# print(a[-2])
# print(a[-1])
# print(a[0])
# print(a[1])
# print(a[2])
# print(a[3])
